default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: ukol6-development

test:
  <<: *default
  database: ukol6-test

production:
  <<: *default
  database: ukol6-production
